#!/bin/sh
#path: /opt/etc/init.d

ENABLED=yes
PROCS=transmission-daemon
ARGS="--config-dir  /opt/etc/transmission/ --logfile /opt/var/log/transmission-daemon.log"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
